version: '3'

#################
# SERVICES
#################
services:

  # Developer environment
  devenv:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 10; do :; done"
    # command: |
    #   /bin/bash -c "
    #     apt-get update && apt-get install -y vim nmap net-tools netcat git python3 python3-pip &&
    #     pip3 install git+https://github.com/vmayoral/scapy@tcpros &&
    #     while sleep 10; do :; done
    #   "
    # python3 examples/6_exploitation_ros.py 192.168.2.6
    networks:
      exploitflownet:
        ipv4_address: 192.168.2.5
    cap_add:
      - NET_ADMIN
      # - ALL

  # Collaborative robot target
  ur3:
    container_name: ur3  
    image: registry.gitlab.com/aliasrobotics/clients/luxembourg-tech-school/targets:ur3_cb3.1_3.12.1
    command: |
      /bin/sh -c "
        echo '2033333333' > /root/ur-serial && truncate -s -1 /root/ur-serial &&
        cd /root/.urcontrol && ln -s urcontrol.conf.UR3 urcontrol.conf &&
        source /root/run_gui.sh && 
        java -Djava.library.path=/root/GUI/lib -jar bin/felix.jar &
        /etc/init.d/ssh start &&
        /bin/sleep 10 && cd /root/.urcontrol/daemon/ && ./run
      "
    networks:
      exploitflownet:
        ipv4_address: 192.168.2.10

  ros:
    container_name: ros  
    image: registry.gitlab.com/aliasrobotics/clients/luxembourg-tech-school/targets:ros_melodic
    command: |
      /bin/bash -c "
        export ROS_MASTER_URI='http://192.168.2.6:11311'
        source /opt/ros/melodic/setup.bash && roscore &
        /bin/sleep 10 && source /opt/ros/melodic/setup.bash && 
        rostopic pub /chatter std_msgs/String "Publisher" -r 5
      "
    networks:
      exploitflownet:
        ipv4_address: 192.168.2.6

  ros2:
      container_name: ros2
      image: registry.gitlab.com/aliasrobotics/clients/luxembourg-tech-school/targets:ros2_dashing
      command: |
        /bin/sh -c "
          source /opt/ros2_ws/install/setup.bash &&
          export ROS_DOMAIN_ID=0 &&
          RMW_IMPLEMENTATION=rmw_fastrtps_cpp ros2 run demo_nodes_cpp talker --ros-args --remap talker:=talker_open
        "
      networks:
        exploitflownet:
          ipv4_address: 192.168.2.7

  px4:
    container_name: px4  
    image: registry.gitlab.com/aliasrobotics/clients/luxembourg-tech-school/targets:px4_1.13.1
    # NOTE: This is a workaround to keep the container running, to launch the PX4 SITL:
    #   /root/entrypoint.sh
    # or manually:
    #   cd /root/Firmware && HEADLESS=1 make px4_sitl gazebo_iris__empty
    command: |
      /bin/bash -c "
        while sleep 10; do :; done        
      "      
    networks:
      exploitflownet:
        ipv4_address: 192.168.2.8

#################
# NETWORKS
#################
networks:
  exploitflownet:
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24