version: '3'

services:
  devenv:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 10; do :; done"
    networks:
      exploitflow-net:
        ipv4_address: 192.168.1.5
    cap_add:
      - NET_ADMIN
      # - ALL

  container-2:
    image: ubuntu:bionic
    # volumes:
    #   # Mount the root folder that contains .git
    #   - ..:/workspace:cached
    command: /bin/sh -c "while sleep 10; do :; done"
    networks:
      exploitflow-net:
        ipv4_address: 192.168.1.6

networks:
  exploitflow-net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24